# Generated by Django 3.2.9 on 2021-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='entregado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
